INSERT INTO `sjp`.`authorities` (`username`, `authority`) VALUES ('admin', 'ROLE_USER');
INSERT INTO `sjp`.`authorities` (`username`, `authority`) VALUES ('admin', 'ROLE_ADMIN');
UPDATE `sjp`.`users` SET `enabled`=1 WHERE  `username`='admin';

INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest1', 'usertest1@gmail.com', 'usertest1', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest2', 'usertest2@gmail.com', 'usertest2', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest3', 'usertest3@gmail.com', 'usertest3', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest4', 'usertest4@gmail.com', 'usertest4', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest5', 'usertest5@gmail.com', 'usertest5', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest6', 'usertest6@gmail.com', 'usertest6', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest7', 'usertest7@gmail.com', 'usertest7', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest8', 'usertest8@gmail.com', 'usertest8', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest9', 'usertest9@gmail.com', 'usertest9', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest10', 'usertest10@gmail.com', 'usertest10', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest11', 'usertest11@gmail.com', 'usertest11', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest12', 'usertest12@gmail.com', 'usertest12', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest13', 'usertest13@gmail.com', 'usertest13', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest14', 'usertest14@gmail.com', 'usertest14', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest15', 'usertest15@gmail.com', 'usertest15', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest16', 'usertest16@gmail.com', 'usertest16', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest17', 'usertest17@gmail.com', 'usertest17', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest18', 'usertest18@gmail.com', 'usertest18', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest19', 'usertest19@gmail.com', 'usertest19', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest20', 'usertest20@gmail.com', 'usertest20', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest21', 'usertest21@gmail.com', 'usertest21', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest22', 'usertest22@gmail.com', 'usertest22', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest23', 'usertest23@gmail.com', 'usertest23', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest24', 'usertest24@gmail.com', 'usertest24', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest25', 'usertest25@gmail.com', 'usertest25', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest26', 'usertest26@gmail.com', 'usertest26', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest27', 'usertest27@gmail.com', 'usertest27', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest28', 'usertest28@gmail.com', 'usertest28', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest29', 'usertest29@gmail.com', 'usertest29', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest30', 'usertest30@gmail.com', 'usertest30', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest31', 'usertest31@gmail.com', 'usertest31', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest32', 'usertest32@gmail.com', 'usertest32', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest33', 'usertest33@gmail.com', 'usertest33', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest34', 'usertest34@gmail.com', 'usertest34', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest35', 'usertest35@gmail.com', 'usertest35', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest36', 'usertest36@gmail.com', 'usertest36', 0);
INSERT INTO `sjp`.`users` (`username`, `email`, `password`, `enabled`) VALUES ('usertest37', 'usertest37@gmail.com', 'usertest37', 0);